// Generated by CoffeeScript 1.7.1
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
  __slice = [].slice;

(function() {
  var hinokiTrace, util;
  hinokiTrace = {};
  if ((typeof window === "undefined" || window === null) && ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null)) {
    util = require('util');
  }
  if (typeof window !== "undefined" && window !== null) {
    window.hinokiTrace = hinokiTrace;
  } else if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    module.exports = hinokiTrace;
  } else {
    throw new Error('either the `window` global or the `module.exports` global must be present');
  }
  hinokiTrace.pad = function(n, length, char) {
    var pad;
    if (length == null) {
      length = 7;
    }
    if (char == null) {
      char = '0';
    }
    pad = new Array(1 + length).join(char);
    return (pad + n).slice(-pad.length);
  };
  hinokiTrace.isObject = function(x) {
    return x === Object(x);
  };
  hinokiTrace.isThenable = function(x) {
    return hinokiTrace.isObject(x) && 'function' === typeof x.then;
  };
  hinokiTrace.newTraceIdGenerator = function() {
    var id;
    id = 0;
    return function() {
      return id++;
    };
  };
  hinokiTrace.valueToString = function(value) {
    if ('object' === typeof value) {
      if (util != null) {
        return util.inspect(value);
      } else {
        return value;
      }
    } else {
      return value;
    }
  };
  hinokiTrace.defaultTraceCallback = function(trace) {
    var prefix;
    prefix = "TRACE " + (hinokiTrace.pad(trace.traceId, 10, ' ')) + " | " + trace.id + " |";
    switch (trace.type) {
      case 'call':
        return console.log(prefix, '<-', trace.args.map(hinokiTrace.valueToString));
      case 'return':
        return console.log(prefix, '->', hinokiTrace.valueToString(trace.value));
      case 'promiseReturn':
        return console.log(prefix, '=>', 'promise');
      case 'promiseResolve':
        return console.log(prefix, '=>', hinokiTrace.valueToString(trace.value));
    }
  };
  return hinokiTrace.newTracingResolver = function(traceFunctions, options) {
    if (options == null) {
      options = {};
    }
    if (options.callback == null) {
      options.callback = hinokiTrace.defaultTraceCallback;
    }
    if (options.nextTraceId == null) {
      options.nextTraceId = hinokiTrace.newTraceIdGenerator();
    }
    return function(container, id, inner) {
      var delegateFactory, factory;
      factory = inner();
      if (factory == null) {
        return;
      }
      if (__indexOf.call(traceFunctions, id) < 0) {
        return factory;
      }
      delegateFactory = function() {
        var dependencies, instance;
        dependencies = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        instance = factory.apply(null, dependencies);
        if ('function' !== typeof instance) {
          throw new Error("tracing " + id + " but factory didn't return a function");
        }
        return function() {
          var args, traceId, valueOrPromise;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          traceId = options.nextTraceId();
          options.callback({
            type: 'call',
            id: id,
            traceId: traceId,
            args: args
          });
          valueOrPromise = instance.apply(null, args);
          if (hinokiTrace.isThenable(valueOrPromise)) {
            options.callback({
              type: 'promiseReturn',
              id: id,
              traceId: traceId,
              promise: valueOrPromise
            });
            return valueOrPromise.then(function(value) {
              options.callback({
                type: 'promiseResolve',
                id: id,
                traceId: traceId,
                value: value
              });
              return value;
            });
          } else {
            options.callback({
              type: 'return',
              id: id,
              traceId: traceId,
              value: valueOrPromise
            });
            return valueOrPromise;
          }
        };
      };
      delegateFactory.$inject = factory.$inject != null ? factory.$inject : hinokiTrace.parseFunctionArguments(factory);
      return delegateFactory;
    };
  };
})();
